default_context:
  project_name: 'ethan-vo-project'
  project_slug: 'ethan-vo-project'
  domain_main: 'xldataproject.xyz'
  domain_staging: 'stag.xldataproject.xyz'
  docker_swarm_stack_name_main: 'xldataproject-xyz'
  docker_swarm_stack_name_staging: 'stag-xldataproject-xyz'
  secret_key: 'VmhUFif34v6whJA2x5NbpYokjcQgyn82'
  first_superuser: 'ethan@xldataproject.xyz'
  first_superuser_password: 'JgQovmqAr26H2ddms9spc7v6Az3b5UWM'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.xldataproject.xyz", "https://stag.xldataproject.xyz", "https://xldataproject.xyz", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@xldataproject.xyz'
  postgres_password: 'A5SvjiQRGLj9TBLLtUJmfFXXX7Cbsy8L'
  pgadmin_default_user: 'ethan@xldataproject.xyz'
  pgadmin_default_user_password: 'JgQovmqAr26H2ddms9spc7v6Az3b5UWM'
  traefik_constraint_tag: 'xldataproject.xyz'
  traefik_constraint_tag_staging: 'stag.xldataproject.xyz'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:JgQovmqAr26H2ddms9spc7v6Az3b5UWM'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
